### ISSUE TITLE
css-code-run

### ISSUE THREAD

**Issue by LearningMonkey61** [LearningMonkey61/css-quick-start-guide#1]
### Context
For each card `div class="card" `, a div with class`demo-code` is the container for the code editing area and the output, shown.
The `textarea` with id  `code1`containes the code where user will write the css-code (sans the  {  +  } ) and will modify the `div class="box"` whose id is `output1`. 
On clicking the play button, the function, `runCSS('code1','output1')` is called, which modifies `output1`. 

## Issue : 
- [ ] Modify `textarea` 's properties, so that, when the play button is clicked, the innerHTML (the CSS code entered by the user) is displayed on alert.

## Contribution-Style
- [ ] fork this project
- [ ] create a new branch 
- [ ] modify code
- [ ] open a pul-request
- [ ] wait for merge

**Comment by h-shams** [comment]
hi @LearningMonkey61, you want to just alert the code or applying the css code to the box?

**Comment by LearningMonkey61** [comment]
> hi @LearningMonkey61, you want to just alert the code or applying the css code to the box?

The final outcome is indeed to apply the CSS code to the box, the exact mechanism for which I would be detailing in another issue. This issue only deals with the proper " code-transfer " from the textarea to any other place where we might want to send it.

By the way, this repository is for teaching the basics of open-source contribution, to my college juniors by helping them solve simple issues.

**But, feel free to contribute!**
